### Testing Python ###

The goal is to setup a testing enviroment and provide testig to quickly assess the status

In [1]:
print ("hello world")

hello world


In [2]:
import sys
print(sys.version)

3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]


In [5]:
conda list env

# packages in environment at C:\Users\Python\anaconda3:
#
# Name                    Version                   Build  Channel
conda-env                 2.6.0                         1  

Note: you may need to restart the kernel to use updated packages.


## Testing Numpy Package ##

In [9]:
#Importing numpy package
import numpy as np

#creating a numpy matrix object
print("creating new matrix a:")
a = np.arange(15).reshape(3,5)
print(a)

creating new matrix a:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
print(a.shape)

(3, 5)
